### ISSUE TITLE
Doesn't work in Laravel Nova

### ISSUE THREAD

**Issue by DianaR19** [TowelSoftware/tailwindcss-toggle#2]

**Comment by nerdalertdk** [comment]
Not testet Nova, but you are more then welcome to donate so I can get nova to test ;)

**Comment by kamilkozak** [comment]
Any updates on this? I have the same issue.

**Comment by nerdalertdk** [comment]
Not testet Nova, but you are more then welcome to donate so I can get nova to test ;)
